Introduction
NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for multidimensional arrays, mathematical functions, and a wide range of operations on arrays. In this guided lab, you will dive into the world of NumPy and learn how to efficiently manipulate arrays, perform mathematical operations, and solve common data science tasks using this powerful library.

Example 1: 

Import NumPy

Open a Python environment (e.g., Jupyter Notebook). Import the NumPy library using import numpy as np.

In [1]:
import numpy as np


Example 2: Creating NumPy Arrays

Create a 1D NumPy array from a Python list.

Create a 2D NumPy array from a nested Python list.

Explore the attributes of NumPy arrays such as shape, size, and data type.

In [ ]:
import numpy as np  # Import the NumPy library with the alias 'np'

# Create a 1D NumPy array from a standard Python list
python_list_1d = [1, 2, 3, 4, 5]
numpy_array_1d = np.array(python_list_1d)

# Create a 2D NumPy array from a nested Python list (list of lists)
python_list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_array_2d = np.array(python_list_2d)

# Get the shape (dimensions) of the 1D and 2D arrays
shape_1d = numpy_array_1d.shape  # Should return (5,)
shape_2d = numpy_array_2d.shape  # Should return (3, 3)

# Get the total number of elements in each array
size_1d = numpy_array_1d.size  # Total elements in 1D array: 5
size_2d = numpy_array_2d.size  # Total elements in 2D array: 9

# Get the data type of the elements in each array
data_type_1d = numpy_array_1d.dtype  # Typically int64 or int32 depending on system
data_type_2d = numpy_array_2d.dtype  # Same as above

# Print the details of the 1D array
print("1D NumPy Array:")
print("Array:", numpy_array_1d)
print("Shape:", shape_1d)
print("Size:", size_1d)
print("Data Type:", data_type_1d)

# Print the details of the 2D array
print("\n2D NumPy Array:")
print("Array:")
print(numpy_array_2d)
print("Shape:", shape_2d)
print("Size:", size_2d)
print("Data Type:", data_type_2d)


1D NumPy Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64

2D NumPy Array:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data Type: int64


Example 3: Statistical and Mathematical Functions

Perform element-wise addition, subtraction, multiplication, and division on arrays.

Apply basic mathematical functions (e.g., np.sin(), np.exp()) to arrays.

In [4]:
# Perform element-wise operations on arrays
addition_result = numpy_array_1d + 10        # Add 10 to each element in the array
subtraction_result = numpy_array_1d - 2      # Subtract 2 from each element in the array (note: fixed variable name)
multiplication_result = numpy_array_1d * 3   # Multiply each element by 3
division_result = numpy_array_1d / 2         # Divide each element by 2

# Display results of arithmetic operations
print("\nElement-wise Operations on 1D Array:")
print("Original Array:", numpy_array_1d)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)

# Apply basic mathematical functions to arrays
sin_result = np.sin(numpy_array_1d)  # Apply sine function to each element (input in radians)
exp_result = np.exp(numpy_array_1d)  # Apply exponential function (e^x) to each element

# Display results of mathematical function applications
print("\nMathematical Functions Applied to 1D Array:")
print("Original Array:", numpy_array_1d)
print("sin Result:", sin_result)
print("exp Result:", exp_result)



Element-wise Operations on 1D Array:
Original Array: [1 2 3 4 5]
Addition Result: [11 12 13 14 15]
Subtraction Result: [-1  0  1  2  3]
Multiplication Result: [ 3  6  9 12 15]
Division Result: [0.5 1.  1.5 2.  2.5]

Mathematical Functions Applied to 1D Array:
Original Array: [1 2 3 4 5]
sin Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
exp Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


Example 4: Statistical and Mathematical Functions

Calculate the mean, median, and standard deviation of an array.

Find the minimum and maximum values in an array.

In [5]:
# Apply basic mathematical functions to arrays
sin_result = np.sin(numpy_array_1d)  # Compute the sine of each element (input values are in radians)
exp_result = np.exp(numpy_array_1d)  # Compute the exponential (e^x) of each element

# Print the original array and the results of the mathematical functions
print("\nMathematical Functions Applied to 1D Array:")
print("Original Array:", numpy_array_1d)
print("sin Result:", sin_result)  # Shows sine of each value
print("exp Result:", exp_result)  # Shows exponential of each value

# Calculate basic statistics on the 1D array
mean_value = np.mean(numpy_array_1d)     # Calculate the average of the array
median_value = np.median(numpy_array_1d) # Get the middle value when the array is sorted
std_deviation = np.std(numpy_array_1d)   # Compute how spread out the values are (standard deviation)
min_value = np.min(numpy_array_1d)       # Find the smallest value in the array
max_value = np.max(numpy_array_1d)       # Find the largest value in the array

# Print the calculated statistics
print("\nStatistics on 1D Array:")
print("Mean:", mean_value)                # Average of all elements
print("Median:", median_value)            # Middle value of sorted elements
print("Standard Deviation:", std_deviation)  # Measure of how spread out values are
print("Minimum Value:", min_value)        # Smallest element
print("Maximum Value:", max_value)        # Largest element



Mathematical Functions Applied to 1D Array:
Original Array: [1 2 3 4 5]
sin Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
exp Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Statistics on 1D Array:
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Minimum Value: 1
Maximum Value: 5


Example 5: Slicing and Indexing

Slice arrays to extract specific elements or sub-arrays.

Use boolean indexing to filter elements based on conditions.

Combine slicing and indexing techniques to manipulate arrays effectively.

In [7]:
# Slicing and Indexing

# Slice elements from index 1 to 3 (4 is not included)
sliced_array = numpy_array_1d[1:4]  # Example: if array is [1, 2, 3, 4, 5], this gives [2, 3, 4]

# Create a boolean array where each element indicates whether the corresponding value is greater than 3
index_condition = numpy_array_1d > 3  # Example: [False, False, False, True, True]

# Print the result of slicing
print("\nSliced Array:")
print(sliced_array)

# Print the result of boolean indexing
print("\nBoolean Indexing:")
print("Original Array:", numpy_array_1d)
print("Index Condition:", index_condition)  # Shows which elements meet the condition
print("Filtered Elements:", numpy_array_1d[index_condition])  # Only elements where condition is True

# Combining Slicing and Indexing

# First slice from index 1 to 3, then apply a condition to filter values > 3 within that slice
combined_result = numpy_array_1d[1:4][numpy_array_1d[1:4] > 3]

# Print result of combined slicing and indexing
print("\nCombined Slicing and Indexing:")
print("Original Array:", numpy_array_1d)
print("Filtered Elements:", combined_result)  # Elements in index 1–3 that are greater than 3



Sliced Array:
[2 3 4]

Boolean Indexing:
Original Array: [1 2 3 4 5]
Index Condition: [False False False  True  True]
Filtered Elements: [4 5]

Combined Slicing and Indexing:
Original Array: [1 2 3 4 5]
Filtered Elements: [4]


Example 6: Real-world example of using NumPy

Let's consider a real-world example of using NumPy for data manipulation in the context of analyzing temperature data from a weather station.

You have a dataset with daily temperature records for a year, and you want to perform various operations and calculations on this data.

In the following example, we will use NumPy to:

Calculate the mean, median, and standard deviation of the daily temperature data.

Convert the temperatures from Celsius to Fahrenheit.

Identify hot days with temperatures above 30°C.

Count the number of hot days.

Calculate cooling degree days, a measure of cooling requirements based on a specified base temperature.

These operations demonstrate how NumPy can simplify data manipulation and analysis, making it a powerful tool for working with real-world data in various scientific and engineering fields, including meteorology and climate science.

In [ ]:
import numpy as np  # Import the NumPy library

# Suppose you have a year's worth of daily temperature data in Celsius
temperature_data = np.array([
    22.3, 23.1, 24.5, 25.8, 23.6, 26.7, 27.9, 29.2, 30.5, 24.7,
    23.4, 22.1, 25.3, 26.4, 28.7, 29.8, 31.2, 32.4, 30.7, 29.5,
    27.8, 26.6, 23.9, 22.5, 24.1, 25.7, 27.3, 29.6, 31.0, 33.1, 31.9
])

# Calculate basic statistical measures on the temperature data
mean_temperature = np.mean(temperature_data)       # Average temperature
median_temperature = np.median(temperature_data)   # Middle value when sorted
std_deviation_temperature = np.std(temperature_data)  # Spread of values around the mean

# Print the statistics
print("Mean Temperature:", mean_temperature)
print("Median Temperature:", median_temperature)
print("Standard Deviation:", std_deviation_temperature)

# Convert temperatures from Celsius to Fahrenheit using the formula: F = C * 9/5 + 32
temperature_data_fahrenheit = (temperature_data * 9/5) + 32

# Identify days where the temperature exceeded 30°C
hot_days = temperature_data[temperature_data > 30]  # Filter for values > 30

# Count how many days were hotter than 30°C
num_hot_days = len(hot_days)

# Print the number of hot days
print("Number of Hot Days:", num_hot_days)

# Calculate Cooling Degree Days (CDD)
# CDD = sum of (temperature - base temperature) for all days where temperature > base
base_temperature = 20  # Set the base indoor comfort temperature (in °C)
cooling_degree_days = np.sum(np.maximum(temperature_data - base_temperature, 0))  # Only count values above base

# Print the total cooling degree days
print("Cooling Degree Days:", cooling_degree_days)
